[build]
target = "thumbv7em-none-eabihf"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = ["sh", "-c", "elf2flash convert --family 0xada52840 $1 $1.uf2", "--"]
rustflags = [
    "-C",
    "link-arg=-Tlink.x",
    # "-C",
    # "linker=flip-link",
    "-C",
    "codegen-units=1",
]

[env]
DEFMT_LOG = "info"