import { Palette } from "std-widgets.slint";
import { UAppTheme } from "libraries/sleek-ui/ui/sleek-ui/app-theme.slint";

export struct Poi {
    a: angle,
    l: float,
}

export global Globals {
    in property <string> version: "0.1.0";

    in property <bool> hardware-user-btn-pressed;
    callback toggle-btn(bool);
    in property <string> target: "VK2-XXX";
    in property <[Poi]> pois: [{ a: 45deg, l: 0.5 }, { a: -10deg, l: 0.7 }, { a: 150deg, l: 0.4 }];
}

struct ButtonColors  {
    base: color,
    pressed: color,
    hovered: color,
}

struct ModeColors {
    background: color,
    primary: color,
    secondary: color,
    text-primary: color,
    text-secondary: color,
    destructive: color,
}

export global UIPalette {
    // in property <bool> dark-mode: true;
    in property <bool> dark-mode: Palette.color-scheme == ColorScheme.dark;

    property <ModeColors> light-mode-colors: {
        background: #FFFFFF,
        primary: #0E133F,
        secondary: #FFBF63,
        text-primary: #000,
        text-secondary: #6284FF,
        destructive: #FF3B30,
    };

    property <ModeColors> dark-mode-colors: {
        background: #122F7B,
        primary: #0E133F,
        secondary: #FFBF63,
        text-primary: #F4F6FF,
        text-secondary: #F4F6FF,
        destructive: #FF3B30,
    };

    out property <color> background: dark-mode ? dark-mode-colors.background : light-mode-colors.background;
    out property <color> primary: dark-mode ? dark-mode-colors.primary : light-mode-colors.primary;
    out property <color> secondary: dark-mode ? dark-mode-colors.secondary : light-mode-colors.secondary;
    out property <color> text-primary: dark-mode ? dark-mode-colors.text-primary : light-mode-colors.text-primary;
    out property <color> text-secondary: dark-mode ? dark-mode-colors.text-secondary : light-mode-colors.text-secondary;
    out property <color> destructive: dark-mode ? dark-mode-colors.destructive : light-mode-colors.destructive;

    // Fixed (non-themeable) colors
    out property <color> push-button-text-color: white;

    // Color of the home/settings/ink buttons on the left side bar
    out property <color> active-page-icon-color: root.dark-mode ? #6284FF : #122F7B;
    out property <color> inactive-page-icon-color: #BDC0D1;
    out property <color> neutral-box: #BDC0D1;
    out property <color> secondary-foreground-color: root.dark-mode ? #C1C3CA : #6C6E7A;

    // Color used for the border / outline of items that can be clicked on, such as the
    // "Print"/"Scan" buttons, the printer queue items (for expansion) or controls such
    // as the combo box or spin box.
    out property <color> control-secondary: #6284FF;
    out property <color> control-foreground: root.dark-mode ? white : #122F7B;  // FIXME: the night mode color was not part of the design
    out property <color> primary-push-button-base: #6284FF;
    out property <ButtonColors> primary-push-button-colors: {
        base: root.primary-push-button-base,
        pressed: root.primary-push-button-base.darker(40%),
        hovered: root.primary-push-button-base.darker(20%),
    };
    out property <color> secondary-push-button-base: destructive;
    out property <ButtonColors> secondary-push-button-colors: {
        base: root.secondary-push-button-base,
        pressed: root.secondary-push-button-base.darker(40%),
        hovered: root.secondary-push-button-base.darker(20%),
    };

    out property <length> base-font-size: 12px;
    out property <length> button-height: 24px;
    out property <length> button-width: button-height * 2;
}

export global Theme {
    out property <length> font-size-standard: 12px;
}

export component Page inherits Rectangle {
    in property <bool> has-back-button: false;

    callback back;

    background: Palette.alternate-background;
    // Stop accidentally getting clicks dur to animation only moving page half way offscreen
    visible: self.opacity > 0;

    TouchArea { } // protect underneath controls

    if (root.has-back-button): Image {
        x: 0;
        source: @image-url("images/back.svg");
        image-fit: contain;
        colorize: UAppTheme.color-fill;
        width: 14px;
        height: 24px;

        TouchArea {
            clicked => {
                root.back()
            }

            x: -14px;
            height: 200%;
            width: self.height;
        }
    }
}

export component Button {
    callback clicked;
    in property <string> text <=> text.text;
    out property <bool> pressed: touch.pressed;
    in property <bool> checkable;
    in-out property <bool> checked;
    in property <length> font-size <=> text.font-size;
    in property <color> background: UIPalette.background;
    Rectangle {
        border-width: 1px;
        border-radius: 2px;
        border-color: UIPalette.text-primary;
        background: (touch.pressed || root.checked) ? UIPalette.secondary : root.background;
    }

    horizontal-stretch: 0;
    vertical-stretch: 0;
    min-height: max(32px, l.min-height);
    l := HorizontalLayout {
        padding-left: 10px;
        padding-right: 10px;
        padding-top: 3px;
        padding-bottom: 3px;
        text := Text {
            color: UIPalette.text-primary;
            horizontal-alignment: center;
            vertical-alignment: center;
            font-size: 16px;
        }
    }

    touch := TouchArea {
        clicked => {
            if (root.checkable) {
                root.checked = !root.checked;
            }
            root.clicked();
        }
    }

    @children
}

export component Toggle inherits Rectangle {
    callback clicked();
    in-out property <bool> on;
    width: UIPalette.button-width;
    height: UIPalette.button-height;

    Rectangle {
        width: UIPalette.button-width;
        height: UIPalette.button-height;
        background: on ? blue : gray;
        animate background {
            duration: 100ms;
            easing: ease;
        }
        border-radius: self.height / 2;

        Text {
            text: on ? "On" : "Off";
            x: on ? 8px : parent.width - 50px;
            color: white;
            font-size: Theme.font-size-standard;
        }

        Rectangle {
            width: parent.height - 4px;
            height: parent.height - 4px;
            x: on ? parent.width - (parent.height - 2px) : 2px;
            animate x {
                duration: 100ms;
                easing: ease;
            }
            y: 2px;
            background: white;
            border-radius: (parent.height - 4px) / 2;
        }
    }

    TouchArea {
        clicked => {
            on = !on;
            root.clicked();
        }
    }
}
