import { Globals } from "common.slint";
import { RadarPage, SettingsPage } from "page.slint";

export { Globals }

export component MainWindow inherits Window {
    height: 320px;
    width: 172px;
    in-out property <int> active-page: 0;
    out property <length> raw-canvas-width <=> radar-page.raw-canvas-width;
    out property <length> raw-canvas-height <=> radar-page.raw-canvas-height;
    out property <length> raw-canvas-x <=> radar-page.raw-canvas-x;
    out property <length> raw-canvas-y <=> radar-page.raw-canvas-y;

    window := VerticalLayout {
        height: 100%;
        alignment: stretch;

        main-view := Rectangle {
            vertical-stretch: 1;
            property <duration> page-animation-duration: 250ms;

            radar-page := RadarPage {
                height: 100%;
                property <int> pageNumber: 0;
                opacity: root.active-page == pageNumber ? 1 : 0;

                settings-triggered => {
                    root.active-page = 1;
                }

                animate opacity { duration: main-view.page-animation-duration; }
            }

            SettingsPage {
                height: 100%;
                property <int> pageNumber: 1;
                opacity: root.active-page == pageNumber ? 1 : 0;
                x: root.active-page == pageNumber ? 0 : root.width;

                back => {
                    root.active-page = 0;
                }

                animate opacity { duration: main-view.page-animation-duration; }
                animate x { duration: main-view.page-animation-duration; }
            }
        }
    }
}
