[package]
name = "lsm6ds3"
version = "0.1.0"
edition = "2024"
description = "I2C driver for the ST LSM6DS3 IMU, built with the `device-driver` crate"


[dependencies]
device-driver = { version = "1.0", default-features = false, features = [
    "dsl",
] }
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"

[dev-dependencies]
linux-embedded-hal = "0.4"
